name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: deployment to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fullstack-bloglist-test-app"
          heroku_email: "kjuliusm@gmail.com"
          healthcheck: "https://fullstack-bloglist-test-app.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          appdir: "server"