name: Test pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install server
        run: |
          cd server
          npm install
      - name: npm install client
        run: |
          cd client
          npm install
      - name: lint server
        run: |
          cd server
          npm run lint
      - name: lint client
        run: |
          cd client
          npm run eslint          
      - name: build client
        run: |
          cd client
          npm run build
      - name: test server
        run: |
          cd server
          npm run test
        env:
          SECRET: ${{ secrets.SECRET }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      - name: test client
        run: |
          cd client
          npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: client
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3000
        env:
          SECRET: ${{ secrets.SECRET }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}